import os
from serpapi import GoogleSearch
from langchain_core.tools import tool

@tool
def search_flights(query: str) -> str:
    """Search for flights based on the user's travel request.
    Input should be a natural language query like 'flights from Delhi to Amsterdam October 1 to 7'
    """
    try:
        search = GoogleSearch({
            "q": f"flights {query}",
            "api_key": os.getenv("SERPAPI_API_KEY"),
            "engine": "google",
            "num": 5
        })
        results = search.get_dict()
        organic = results.get("organic_results", [])
        if not organic:
            return "No flight results found. Try a different query."
        
        output = "✈️ Flight Options Found:\n\n"
        for i, r in enumerate(organic[:4], 1):
            output += f"{i}. {r.get('title', 'N/A')}\n"
            output += f"   {r.get('snippet', '')}\n"
            output += f"   Link: {r.get('link', '')}\n\n"
        return output
    except Exception as e:
        return f"Error searching flights: {str(e)}"


@tool
def search_hotels(query: str) -> str:
    """Search for hotels at the destination.
    Input should be like 'hotels in Amsterdam October 1 to 7'
    """
    try:
        search = GoogleSearch({
            "q": f"hotels {query}",
            "api_key": os.getenv("SERPAPI_API_KEY"),
            "engine": "google",
            "num": 5
        })
        results = search.get_dict()
        organic = results.get("organic_results", [])
        if not organic:
            return "No hotel results found."
        
        output = "🏨 Hotel Options Found:\n\n"
        for i, r in enumerate(organic[:4], 1):
            output += f"{i}. {r.get('title', 'N/A')}\n"
            output += f"   {r.get('snippet', '')}\n"
            output += f"   Link: {r.get('link', '')}\n\n"
        return output
    except Exception as e:
        return f"Error searching hotels: {str(e)}"


@tool  
def send_travel_email(recipient_email: str, travel_plan: str) -> str:
    """Send the finalized travel plan to the user's email as HTML.
    Args:
        recipient_email: The user's email address
        travel_plan: The complete travel plan text
    """
    import sendgrid
    from sendgrid.helpers.mail import Mail
    
    try:
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 30px; border-radius: 12px; color: white; text-align: center; margin-bottom: 30px;">
                <h1>✈️ Your Travel Plan is Ready!</h1>
                <p>Here's your personalized itinerary from your AI Travel Agent</p>
            </div>
            <div style="background: #f9f9f9; padding: 25px; border-radius: 8px; border-left: 4px solid #667eea;">
                <pre style="white-space: pre-wrap; font-family: Arial, sans-serif; font-size: 15px; line-height: 1.7; color: #333;">
{travel_plan}
                </pre>
            </div>
            <div style="text-align: center; margin-top: 30px; color: #888; font-size: 13px;">
                <p>🤖 Generated by AI Travel Agent powered by LangGraph</p>
            </div>
        </body>
        </html>
        """
        
        sg = sendgrid.SendGridAPIClient(api_key=os.getenv("SENDGRID_API_KEY"))
        message = Mail(
            from_email=os.getenv("SENDGRID_FROM_EMAIL"),
            to_emails=recipient_email,
            subject="✈️ Your AI Travel Plan",
            html_content=html_content
        )
        response = sg.send(message)
        
        if response.status_code in [200, 202]:
            return f"✅ Travel plan successfully sent to {recipient_email}!"
        else:
            return f"⚠️ Email sending returned status {response.status_code}"
    except Exception as e:
        return f"❌ Error sending email: {str(e)}"
